stack-setup:
    script:
        - stack setup

build:
    script:
        - stack update
        - stack build

test:
    script:
        - stack build --test --coverage

hamsql-binary:
    only:
        - tags
    script:
        - make
        - cp dist/build/hamsql/hamsql ./
    artifacts:
        paths:
            - hamsql
