build-hamsql:
    script:
        - cabal update
        - cabal sandbox init
        - cabal install --dependencies-only --enable-tests --disable-optimization
        - make pebble
        - cabal configure --enable-tests --enable-coverage --disable-optimization
        - cabal test
        - tail -n 2 dist/hpc/vanilla/html/hamsql-tests/hpc_index.html

hamsql-binary:
    only:
        - tags
    script:
        - make
        - cp dist/build/hamsql/hamsql ./
    artifacts:
        paths:
            - hamsql
