stack-setup:
    script:
        - stack setup

build:
    script:
        - stack update
        - stack build --fast

test:
    script:
        - stack test --fast --coverage

hamsql-binary:
    only:
        - tags
    script:
        - stack build
        - cp `stack path --dist-dir`/build/hamsql/hamsql ./
    artifacts:
        paths:
            - hamsql
